### ISSUE TITLE
test_uint32_shr fails

### ISSUE THREAD

**Issue by bitcartel** [zcash-hackworks/sapling-crypto#76]
```
rustup show
Default host: x86_64-unknown-linux-gnu

stable-x86_64-unknown-linux-gnu (default)
rustc 1.26.2 (594fb253c 2018-06-01)




cargo test test_uint32_shr
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running /home/simon/projects/sapling-crypto/target/debug/deps/sapling_crypto-55bb314f5fca8fb9

running 1 test
test circuit::uint32::test::test_uint32_shr ... FAILED

failures:

---- circuit::uint32::test::test_uint32_shr stdout ----
	thread 'circuit::uint32::test::test_uint32_shr' panicked at 'attempt to shift right with overflow', src/circuit/uint32.rs:662:42
note: Run with `RUST_BACKTRACE=1` for a backtrace.


failures:
    circuit::uint32::test::test_uint32_shr

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 84 filtered out




RUST_BACKTRACE=1 cargo test test_uint32_shr
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running /home/simon/projects/sapling-crypto/target/debug/deps/sapling_crypto-55bb314f5fca8fb9

running 1 test
test circuit::uint32::test::test_uint32_shr ... FAILED

failures:

---- circuit::uint32::test::test_uint32_shr stdout ----
	thread 'circuit::uint32::test::test_uint32_shr' panicked at 'attempt to shift right with overflow', src/circuit/uint32.rs:662:42
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:207
   3: std::panicking::default_hook
             at libstd/panicking.rs:217
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:402
   5: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:349
   6: rust_begin_unwind
             at libstd/panicking.rs:325
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:72
   8: core::panicking::panic
             at libcore/panicking.rs:51
   9: sapling_crypto::circuit::uint32::test::test_uint32_shr
             at src/circuit/uint32.rs:662
  10: sapling_crypto::__test::TESTS::{{closure}}
             at src/circuit/uint32.rs:655
  11: core::ops::function::FnOnce::call_once
             at /checkout/src/libcore/ops/function.rs:223
  12: <F as alloc::boxed::FnBox<A>>::call_box
             at libtest/lib.rs:1453
             at /checkout/src/libcore/ops/function.rs:223
             at /checkout/src/liballoc/boxed.rs:784
  13: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102


failures:
    circuit::uint32::test::test_uint32_shr

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 84 filtered out

error: test failed, to rerun pass '--lib'
```

**Comment by ebfull** [comment]
It's just a debug assertion (faulty test) which appears when you don't run tests in `--release` mode, it should be changed to unchecked or wrapping shift or maybe the test should be modified.

**Comment by defuse** [comment]
Proposed fix in: https://github.com/zcash-hackworks/sapling-crypto/pull/98

**Comment by str4d** [comment]
Fixed in https://github.com/zcash/librustzcash/pull/81.
